### ISSUE TITLE
Исключение IllegalArgumentException не выкидывается при отрицательном значении minBalance

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#10]
# Описание
Параметры переменной minBalance (минимальный баланс) допускают отрицательные значения, что противоречит техническому заданию.
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java)  в IDEA
2. Создать объект из класса SavingAccount 
3. Выставить значение переменной initialBalance (начальный баланс) равное 1 500
4. Выставить значение переменной minBalance (минимальный баланс) равное -1
5. Выставить значение переменной maxBalance (максимальный баланс) равное 400 000
6. Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 4
7. Запустить Test
8. Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли “"Минимальный баланс не может быть отрицательным, а у вас: " + minBalance ”

*Фактический результат:*   Вывод сообщения в консоли о переменной minBalance со значением -1
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L26
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235269305-ea995e93-2f3b-4ea6-86fa-7949972c6aec.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
•	**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
Метод дописан, исключения выбрасываются, но тесты не проходят из-за значений в самих теста.  Возможно нужно будет переписать тесты на исключения, на тесты такого плана : https://github.com/TatianaSm77/Team-project-banking-account/blob/bcfdc6e1db092c01fa2ad02da43fafb404ef021f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L24

![Issues 10-15_test](https://user-images.githubusercontent.com/125288096/235358470-e8bf9c0f-dd5b-450f-8111-8ada16dde07f.png)
![Issues 10-15](https://user-images.githubusercontent.com/125288096/235358471-267ef95b-aca6-4fb4-9d79-8e23073a96e3.png)
![Issues 10-15_test_1](https://user-images.githubusercontent.com/125288096/235358473-0c00e260-9b9e-4530-a96e-317ce7c38114.png)
