### ISSUE TITLE
Исключение IllegalArgumentException не выкидывается при значении minBalance большем, чем значение maxBalance

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#11]
# Описание
Значение переменной minBalance (минимальный баланс) больше, чем значение maxBalance
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения
1.  Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java)  в IDEA
2.  Создать объект из класса SavingAccount 
3.  Выставить значение переменной initialBalance (начальный баланс) равное 1 500
4.  Выставить значение переменной minBalance (минимальный баланс) равное 500 000
5.  Выставить значение переменной maxBalance (максимальный баланс) равное 400 000
6.  Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 4
7.  Запустить Test
8.  Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли “"Минимальный баланс не может быть больше, чем Максимальный баланс"”
*Фактический результат:* Вывод сообщения в консоли о переменной minBalance со значением 500 000
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L35
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235271335-52630b3e-9e1e-455a-abd7-06554233216e.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
•	**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
Смотри комментарии к Issues #10
