### ISSUE TITLE
Исключение IllegalArgumentException не выкидывается при отрицательном значении maxBalance

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#12]
# Описание
Параметры переменной maxBalance (максимальный баланс) можно сделать отрицательным значением.
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Выставить значение переменной initialBalance (начальный баланс) равное 3 750
3. Выставить значение переменной minBalance (минимальный баланс) равное 0
4. Выставить значение переменной maxBalance (максимальный баланс) равное  -1
5. Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 12
6. Запустить Test
7. Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли “"Максимальный баланс не может быть отрицательным, а у вас: " + maxBalance ”
*Фактический результат:* Вывод сообщения в консоли о переменной maxBalance со значением -1
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L50
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235273959-7c600424-fcc6-4f26-9c13-16632bc03613.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
•	**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
Смотри комментарии к Issues #10
