### ISSUE TITLE
Исключение IllegalArgumentException не выкидывается при значении maxBalance меньшем, чем значение minBalance

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#13]
# Описание
Параметры переменной maxBalance (максимальный баланс) могут быть меньше, чем значение minBalance (минимальный баланс)
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект из класса SavingAccount 
3. Выставить значение переменной initialBalance (начальный баланс) равное 11 000
4. Выставить значение переменной minBalance (минимальный баланс) равное  10 000
5. Выставить значение переменной maxBalance (максимальный баланс) равное  5 000
6. Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 12
7. Запустить Test
8. Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли “"Максимальный баланс не может быть меньше, чем Минимальный баланс"”
*Фактический результат:* Вывод сообщения в консоли о переменной maxBalance со значением 5000
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L67
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235274630-8c48fc05-4146-4d21-b370-9d0887b25682.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
•	**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
Смотри комментарии к Issues #10
