### ISSUE TITLE
Исключение IllegalArgumentException не выкидывается при отрицательном значении initialBalance

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#14]
# Описание
Параметры переменной initialBalance (начальный баланс) допускают отрицательное значение, что противоречит техническому заданию.
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения
1.  Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2.  Создать объект из класса SavingAccount 
3.  Выставить значение переменной initialBalance (начальный баланс) равное -1
4.  Выставить значение переменной minBalance (минимальный баланс) равное  0
5.  Выставить значение переменной maxBalance (максимальный баланс) равное  150 000
6.  Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 13
7.  Запустить Test
8.  Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли “"Начальный баланс не может быть меньше, чем Минимальный баланс"”
*Фактический результат:* Вывод сообщения в консоли о переменной initialBalance со значением -1
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L89
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235276785-8bbf7e1b-c423-438c-9fad-2b0fc6e261d0.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
•	**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
Смотри комментарии к Issues #10
