### ISSUE TITLE
Исключение IllegalArgumentException не выкидывается при значении initialBalance большем, чем значение maxBalance

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#15]
# Описание
Параметры переменной initialBalance (начальный баланс) могут быть больше, чем значение maxBalance
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22-L32
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект из класса SavingAccount 
3. Выставить значение переменной initialBalance (начальный баланс) равное 160 000
4. Выставить значение переменной minBalance (минимальный баланс) равное  500
5. Выставить значение переменной maxBalance (максимальный баланс) равное  150 000 
6. Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 13
7. Запустить Test
8. Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли “"Начальный баланс не может быть больше, чем Максимальный баланс"”
*Фактический результат:* Вывод сообщения в консоли о переменной initialBalance со значением 160 000
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L107
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235277337-78e4f118-0024-49cb-8edc-bbde27d557fe.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
•	**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
Смотри комментарии к Issues #10
