### ISSUE TITLE
Отрицательный баланс при сумме покупки amount превышающей остаток на  балансе

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#16]
# Описание
Сумма покупки amount может превышать остаток денежных средств на счёте balance, что противоречит техническому заданию
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект из класса SavingAccount 
3.  Выставить значение переменной initialBalance (начальный баланс) равное 35 000
4.  Выставить значение переменной minBalance (минимальный баланс) равное  500
5.  Выставить значение переменной maxBalance (максимальный баланс) равное  500 000 
6.  Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 16
7.  Вызвать метод pay c аргументом amount (сумма покупки)
8.  Выставить значение переменной amount (сумма покупки) равное 37 000
9.  Запустить Test
10. Посмотреть вывод в консоли

*Ожидаемый результат:*  Вывод сообщения в консоли информации о переменной balance со значением  35 000 
*Фактический результат:* Вывод сообщения в консоли информации о переменной balance со значением  - 2 000 
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L160
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235278120-c7c131fd-ad03-4d67-96ce-f9ac2c66461d.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
![issues 16](https://user-images.githubusercontent.com/125288096/235354418-c46d5d43-69a4-416e-911e-5fc96f48c673.png)
![issues 16_test](https://user-images.githubusercontent.com/125288096/235354427-7b0710f2-dde4-45ce-a3ca-a40c7e15afcb.png)
Метод исправлен, тест проходит
