### ISSUE TITLE
Отрицательный баланс при сумме покупки amount превышающей установленный maxBalance

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#17]
# Описание
Сумма покупки amount может превышать установленный maxBalance (максимальный баланс) сберегательного счёта, что противоречит техническому заданию.
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44
# Шаги воспроизведения
1.  Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2.  Создать объект из класса SavingAccount 
3.  Выставить значение переменной initialBalance (начальный баланс) равное 35 000
4.  Выставить значение переменной minBalance (минимальный баланс) равное  500
5.  Выставить значение переменной maxBalance (максимальный баланс) равное  500 000 
6.  Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 16
7.  Вызвать метод pay c аргументом amount (сумма покупки)
8.  Выставить значение переменной amount (сумма покупки) равное 3 700 000
9.  Запустить Test
10. Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли информации о переменной balance со значением  35 000
*Фактический результат:* Вывод сообщения в консоли информации о переменной balance со значением  - 3 665 000
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L180
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235278650-e2de35c4-48a1-4ce9-97cc-b1b7d64ac616.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
![issues 16_17_test](https://user-images.githubusercontent.com/125288096/235354605-f9c82f52-772a-4125-8b12-8f8018592ef4.png)
![issues 17_test](https://user-images.githubusercontent.com/125288096/235354607-2d807223-0365-403d-997c-a08bc3b93d9c.png)
Метод исправлен, тест проходит
