### ISSUE TITLE
Переменная initialBalance (начальный баланс) не учитывается в итоговом балансе при пополнении счёта 

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#18]
# Описание
При выполнении функции add (пополнение карты на указанную сумму) итоговый баланс не учитывает initialBalance (начальный баланс)
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект из класса SavingAccount 
3. Выставить значение переменной initialBalance (начальный баланс) равное 35 000
4. Выставить значение переменной minBalance (минимальный баланс) равное  500
5. Выставить значение переменной maxBalance (максимальный баланс) равное  500 000 
6. Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 16
7. Вызвать метод pay c аргументом amount (сумма пополнения)
8. Выставить значение переменной amount (суммы пополнения) равное 253 640
9. Запустить Test
 10. Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли переменная balance с учётом initialBalance (начального баланса)  увеличится на amount (сумму пополнения) и будет равна 288 640
*Фактический результат:* Вывод сообщения в консоли переменная balance приняла значение равное amount (сумме пополнения) и равна 253 640
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L227
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235279085-015d6c82-a719-4205-84bd-34de0b000c83.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TIgorT** [comment]
Опечатался в шаге воспроизведения ниже пункт с правильным вариантом:
# Шаги воспроизведения
7. Вызвать метод add c аргументом amount (сумма пополнения)

**Comment by TatianaSm77** [comment]
![issues 18 19](https://user-images.githubusercontent.com/125288096/235354902-995055b0-1ada-4e8c-ba41-57baca2ecbf6.png)
![issues 18_test](https://user-images.githubusercontent.com/125288096/235354903-118d847e-3902-49fe-a432-dba83fb266e2.png)
Метод исправлен, тест проходит
