### ISSUE TITLE
Не отображается корректно итоговый баланс в пределах допустимого максимального значения maxBalance при пополнении счёта

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#19]
# Описание
Не отображается корректно balance (итоговый баланс) в пределах допустимого максимального значения maxBalance (максимальный баланс) при пополнении счёта
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект из класса SavingAccount 
3. Выставить значение переменной initialBalance (начальный баланс) равное 35 000
4. Выставить значение переменной minBalance (минимальный баланс) равное  500
5. Выставить значение переменной maxBalance (максимальный баланс) равное  500 000
6. Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 16
7. Вызвать метод add c аргументом amount (сумма пополнения)
8. Выставить значение переменной amount (суммы пополнения) равное 465 000
9. Запустить Test
10. Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли   значение переменной maxBalance (максимальный баланс) составляет 500 000
*Фактический результат:* Вывод сообщения в консоли Переменная balance приняла значение равное initialBalance (начальный баланс) 35 000
# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L245
# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235279595-d270cef5-6fdf-478b-90d8-efe498a6acef.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
![issues 19_test](https://user-images.githubusercontent.com/125288096/235354783-bfdff0e2-94b1-4cee-89df-127e385cc861.png)
![issues 19](https://user-images.githubusercontent.com/125288096/235354784-56a4cd5c-0cc0-4ee3-9948-b1d82df2cb68.png)
Метод исправлен, тест проходит
