### ISSUE TITLE
Исключение IllegalArgumentException не выбрасывается при отрицательном балансе

### ISSUE THREAD

**Issue by TatianaSm77** [TatianaSm77/Team-project-banking-account#2]
#Описание
При создании кредитного счета с отрицательным начальным балансом не выбрасывается исключение IllegalArgumentException.

# Локализация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/bcfdc6e1db092c01fa2ad02da43fafb404ef021f/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Выставить отрицательное значение переменной initialBalance и положительное для creditLimit и rate 
3. Запустить test
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* выбрасывается исключение IllegalArgumentException тест проходит
*Фактический результат:* не выбрасывается исключение IllegalArgumentException тест падает

#Тест

https://github.com/TatianaSm77/Team-project-banking-account/blob/bcfdc6e1db092c01fa2ad02da43fafb404ef021f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L24

# Скриншот
![issues_1](https://user-images.githubusercontent.com/125288096/234929637-81850892-9866-4208-9b5d-86294a42ef85.png)

# Окружение
* **Операционная система:** Windows 11 Pro
*  **IDE:** IntelliJ IDEA Community Edition 2022.3.2
*  **Java:** OpenJKD 11

**Comment by TIgorT** [comment]
Дописал данное исключение, указанный тест проходит.
# Скриншот
![Team-project-banking-account – CreditAccountTest j](https://user-images.githubusercontent.com/125376916/235515581-f5601507-bb91-43fc-a41a-6b9ab4958ebb.png)
