### ISSUE TITLE
Переменная rate в функции yearChange не имеет ограничение на максимально допустимое значение

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#20]
# Описание
Переменная rate (ставка в процентах годовых на остаток) в функции yearChange (расчёта процентов на остаток счёта) не имеет ограничение на максимально допустимое значение
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java) в IDEA
2. Создать объект из класса SavingAccount
3. Выставить значение переменной initialBalance (начальный баланс) равное 35 000
4. Выставить значение переменной minBalance (минимальный баланс) равное  500
5. Выставить значение переменной maxBalance (максимальный баланс) равное  500 000 
6. Выставить значение переменной rate (ставка в процентах годовых на остаток) равное 1 060
7. Вызвать метод yearChange (расчёта процентов на остаток счёта)
8. Запустить Test
9. Посмотреть вывод в консоли

*Ожидаемый результат:* Вывод сообщения в консоли Расчётное значение равное нулю 
*Фактический результат:* Вывод сообщения в консоли Функция выводит расчётное значение равное 371 000 

# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L311

# Скриншот
![изображение](https://user-images.githubusercontent.com/125376916/235280296-865a104c-81fc-4902-ab89-873cb57915e2.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
В условии не говориться о  максимально допустимом значении, говориться только  о том, что оно может быть неотрицательным. 
Поэтому метод yearChange  написан корректно. Он вычисляет проценты, полученные на остаток на счете, на основе текущей про
центной ставки, делением баланса на 100 и умножением на процентную ставку

![issues_20](https://user-images.githubusercontent.com/125288096/235355904-2d26f9a1-433b-4533-bcc4-d26fef17f691.png)
