### ISSUE TITLE
Переменная initialBalance (начальный баланс) в классе SavingAccount  не заведена

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#21]
# Описание
Переменная initialBalance (начальный баланс) в классе SavingAccount  не заведена
# Локация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/31ddeaf3b9f198af37dd1528e655f52ff8aea093/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L9-L11
# Шаги воспроизведения
1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA

*Ожидаемый результат:* Переменная protected int initialBalance заведена в классе SavingAccount
*Фактический результат:* Переменная отсутствует
# Скриншот
![Team-project-banking-account – SavingAccount java ](https://user-images.githubusercontent.com/125376916/235280561-9e861b57-b211-464a-b1f5-ae2169fd1712.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
**Java:**  OpenJDK 11

@TatianaSm77

**Comment by TatianaSm77** [comment]
Так как переменная  initialBalance будет использоваться только в конструкторе класса SavingAccount для инициализации баланса экземпляра класса, то объявление ее как параметра конструктора public SavingAccount(int initialBalance, int minBalance, int maxBalance, int rate) будет достаточным. Значение переменной не используется в других методах класса.
