### ISSUE TITLE
Getter переменной initialBalance (начальный баланс) в классе SavingAccount не заведён

### ISSUE THREAD

**Issue by TIgorT** [TatianaSm77/Team-project-banking-account#22]
# Описание
Getter переменной initialBalance (начальный баланс) в классе SavingAccount не заведён
# Локация дефекта

# Шаги воспроизведения

1. Открыть [Код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/saving/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA

*Ожидаемый результат:* Getter переменной initialBalance заведён в классе SavingAccount
*Фактический результат:* Getter переменной initialBalance не заведён 
# Скриншот
![Team-project-banking-account – SavingAccount java ](https://user-images.githubusercontent.com/125376916/235280741-582b751f-7b85-44d6-b5c4-6e6259d29640.png)

# Окружение
•	**Операционная система:** Windows 10 Pro, версия 21H2
•	**IDE:**  2022.3.2 (Community Edition)
**Java:**  OpenJDK 11
 
@TatianaSm77

**Comment by TatianaSm77** [comment]
Переменная initialBalance является параметром конструктора и уже инициализирует поле balance при создании объекта. К тому же, поле balance уже имеет свой геттер метод, который позволяет получить значение баланса. Если бы initialBalance была бы полем класса, то был бы необходимость в геттере для ее получения.
