### ISSUE TITLE
Исключение IllegalArgumentException не выбрасывается при отрицательном кредитном лимите

### ISSUE THREAD

**Issue by TatianaSm77** [TatianaSm77/Team-project-banking-account#3]
#Описание
При создании кредитного счета с отрицательным кредитным лимитом выбрасывается исключение IllegalArgumentException.

# Локализация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/bcfdc6e1db092c01fa2ad02da43fafb404ef021f/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Выставить отрицательное значение переменной initialBalance и положительное для creditLimit и rate 
3. Запустить test
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* выбрасывается исключение IllegalArgumentException тест проходит
*Фактический результат:* не выбрасывается исключение IllegalArgumentException тест падает

#Тест

https://github.com/TatianaSm77/Team-project-banking-account/blob/bcfdc6e1db092c01fa2ad02da43fafb404ef021f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L31

# Скриншот
![issues_2](https://user-images.githubusercontent.com/125288096/234931658-2a760f14-764c-453b-b110-8ac5678abb7f.png)

# Окружение
* **Операционная система:** Windows 11 Pro
*  **IDE:** IntelliJ IDEA Community Edition 2022.3.2
*  **Java:** OpenJKD 11

**Comment by TIgorT** [comment]
Дописал данное исключение, указанный тест проходит.
![Team-project-banking-account – CreditAccountTest j](https://user-images.githubusercontent.com/125376916/235516958-3d6310b3-9ad2-4b66-a782-07ef4593a0c2.png)
