### ISSUE TITLE
Баланс не увеличивается на соответствующую сумму

### ISSUE THREAD

**Issue by TatianaSm77** [TatianaSm77/Team-project-banking-account#4]
#Описание
При добавлении положительной суммы на счет с положительным балансом, баланс не увеличивается на соответствующую сумму

# Локализация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L66

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать новый экземпляр класса CreditAccount с положительными значениями
3. Вызвать метод add 
3. Запустить test
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* баланс увеличился на сумму пополнения
*Фактический результат:* баланс стал равным сумме пополнения

# Тест

https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L17

# Скриншот
![issues_3](https://user-images.githubusercontent.com/125288096/234965825-ffce9cd1-9e0d-4a4c-91f7-317b57e917f8.png)

# Окружение
* **Операционная система:** Windows 11 Pro
*  **IDE:** IntelliJ IDEA Community Edition 2022.3.2
*  **Java:** OpenJKD 11

**Comment by TIgorT** [comment]
Откорректировал метод add, указанный тест проходит.
# Скриншот
![Team-project-banking-account – CreditAccountTest j](https://user-images.githubusercontent.com/125376916/235518314-d1087085-78fb-4998-b6d7-c50a5e837f2d.png)
