### ISSUE TITLE
Отрицательный баланс при покупке 

### ISSUE THREAD

**Issue by TatianaSm77** [TatianaSm77/Team-project-banking-account#5]
#Описание
При выполнении покупки в пределах кредитного лимита на счете с положительным балансом, баланс становиться отрицательным

# Локализация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать новый экземпляр класса CreditAccount с положительными значениями
3. Вызвать метод pay c аргументом меньше значения initialBalace
3. Запустить test
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* баланс остался положительным
*Фактический результат:* баланс стал отрицательным 

# Тест

https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L45

# Скриншот
![issues_4](https://user-images.githubusercontent.com/125288096/234970027-8eab2e09-7465-4451-bb93-3dd89ba81f2b.png)

# Окружение
* **Операционная система:** Windows 11 Pro
*  **IDE:** IntelliJ IDEA Community Edition 2022.3.2
*  **Java:** OpenJKD 11

**Comment by TIgorT** [comment]
Откорректировал метод pay, указанный тест проходит.
# Скриншот
![Team-project-banking-account – CreditAccountTest j](https://user-images.githubusercontent.com/125376916/235519073-e14a4750-7232-42f7-858b-bec1472de7aa.png)
