### ISSUE TITLE
Отрицательный баланс при покупке на сумму равной балансу

### ISSUE THREAD

**Issue by TatianaSm77** [TatianaSm77/Team-project-banking-account#6]
#Описание
При выполнении покупки на сумму, равную текущему балансу, на счете становится отрицательный баланс

# Локализация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать новый экземпляр класса CreditAccount с положительными значениями
3. Вызвать метод pay c аргументом равным значению initialBalace
3. Запустить test
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* на счете должен остаться ноль
*Фактический результат:* баланс стал отрицательным 

# Тест

https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L52

# Скриншот
![issues_5](https://user-images.githubusercontent.com/125288096/234972231-080ceac4-5672-4326-b797-dc58cbf863e2.png)

# Окружение
* **Операционная система:** Windows 11 Pro
*  **IDE:** IntelliJ IDEA Community Edition 2022.3.2
*  **Java:** OpenJKD 11

**Comment by TIgorT** [comment]
Откорректировал метод pay, указанный тест проходит.
# Скриншот
![Team-project-banking-account – CreditAccountTest j](https://user-images.githubusercontent.com/125376916/235519574-8613d8b1-f032-4b3e-9439-bfca9a5e63da.png)
