### ISSUE TITLE
Остаток на балансе рассчитывается некорректно

### ISSUE THREAD

**Issue by TatianaSm77** [TatianaSm77/Team-project-banking-account#7]
#Описание
 При выполнении покупки на сумму большую, чем текущий баланс счета, но в пределе initialBalance, creditLimit, баланс рассчитывается некорректно 

# Локализация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать новый экземпляр класса CreditAccount с положительными значениями
3. Вызвать метод pay c положительными аргументами, но не больше суммы (initialBalance, creditLimit)
3. Запустить test
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* баланс уменьшается на сумму покупки
*Фактический результат:* баланс стал равным отрицательному значению суммы покупки

# Тест

https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L58

# Скриншот
![issues_6](https://user-images.githubusercontent.com/125288096/234974366-9b7ae880-2fb9-449f-9640-1bad1ceb43aa.png)

# Окружение
* **Операционная система:** Windows 11 Pro
*  **IDE:** IntelliJ IDEA Community Edition 2022.3.2
*  **Java:** OpenJKD 11

**Comment by TIgorT** [comment]
Откорректировал метод pay, указанный тест проходит.
# Скриншот
![Team-project-banking-account – CreditAccountTest j](https://user-images.githubusercontent.com/125376916/235520244-e988b19d-ab8a-440d-8d91-fe0074301870.png)
