### ISSUE TITLE
Неверный баланс счета после покупки на сумму, превышающую кредитный лимит

### ISSUE THREAD

**Issue by TatianaSm77** [TatianaSm77/Team-project-banking-account#8]
#Описание
 При покупке на сумму, превышающую кредитный лимит, баланс счета не изменяется корректно. Вместо этого, фактический баланс счета становится отрицательным, в то время как ожидаемый баланс счета должен оставаться неизменным.

# Локализация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать новый экземпляр класса CreditAccount с положительными значениями
3. Вызвать метод pay c положительными аргументами, и больше суммы (initialBalance, creditLimit)
3. Запустить test
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* баланс счета должен оставаться неизменным после попытки провести покупку на сумму, превышающую кредитный лимит
*Фактический результат:* баланс счета становится отрицательным

# Тест

https://github.com/TatianaSm77/Team-project-banking-account/blob/d8df5e421384ad6445759d78f2868d27951e3d9c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L66

# Скриншот
![issues_7](https://user-images.githubusercontent.com/125288096/234984076-fd7d866b-ed6e-409c-819a-8423f6a796b7.png)

# Окружение
* **Операционная система:** Windows 11 Pro
*  **IDE:** IntelliJ IDEA Community Edition 2022.3.2
*  **Java:** OpenJKD 11

**Comment by TIgorT** [comment]
Откорректировал метод pay, указанный тест проходит.
# Скриншот
![Team-project-banking-account – CreditAccountTest j](https://user-images.githubusercontent.com/125376916/235520853-7d97f0f2-4114-4109-9c34-58217f46e012.png)
