### ISSUE TITLE
При положительном балансе применяется операция расчёта процентов на отрицательный баланс счёта

### ISSUE THREAD

**Issue by TatianaSm77** [TatianaSm77/Team-project-banking-account#9]
#Описание
При положительном балансе применяется операция расчёта процентов на отрицательный баланс счёта. Mетод yearChange() для объекта CreditAccount не возвращает 0.

# Локализация дефекта
https://github.com/TatianaSm77/Team-project-banking-account/blob/dd061c47951f2c219b3aff9a1f2b8c4a5476b502/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L83

# Шаги воспроизведения

1. Открыть [код программы](https://github.com/TatianaSm77/Team-project-banking-account/blob/credit/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java) в IDEA
2. Создать новый экземпляр класса CreditAccount с положительными значениями
3. Вызвать метод yearChange() для объекта account.
3. Запустить test
4. Посмотреть на вывод в консоли

*Ожидаемый результат:* Тест успешно проходит, ожидаемый результат - 0.
*Фактический результат:* Тест не проходит, фактический результат - 30.

# Тест
https://github.com/TatianaSm77/Team-project-banking-account/blob/dd061c47951f2c219b3aff9a1f2b8c4a5476b502/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L105

# Скриншот
![issues_8](https://user-images.githubusercontent.com/125288096/235166364-7ef1c859-63d3-4842-b9b4-a29b3c2193ce.png)

# Окружение
* **Операционная система:** Windows 11 Pro
*  **IDE:** IntelliJ IDEA Community Edition 2022.3.2
*  **Java:** OpenJKD 11

**Comment by TIgorT** [comment]
Откорректировал метод yearChange, указанный тест проходит.
# Скриншот
![Team-project-banking-account – CreditAccountTest j](https://user-images.githubusercontent.com/125376916/235521484-6538ccfa-f7b4-430e-84ea-58b4bba579c6.png)
